export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
// MINE
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGGED_FAILED = 'LOGGED_FAILED';
export const LOAD_CARS_SUCCESS = 'LOAD_CARS_SUCCESS';
export const LOAD_CARS_FAILED = 'LOAD_CARS_FAILED';
export const SEND_DEVIS_SUCCESS = 'SEND_DEVIS_SUCCESS';
export const SEND_DEVIS_FAILED= 'SEND_DEVIS_FAILED';